services:
  postgres:
    image: postgres:16-alpine
    container_name: erp-loja-ferragem-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp
      POSTGRES_DB: erp_loja_ferragem
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
